### ISSUE TITLE
I think python3-venv is included in python installs

### ISSUE THREAD

**Issue by sgoggins** [augurlabs/augur_view#2]
I have had Fedora machines on which it does not come installed. I believe its an operating system level package: 

```
sudo apt install python3-venv
```

Works on Ubuntu. 

``` 
pip install python3-venv
```

Generates this error on Ubuntu. 
```
(augur_view) sean@augur:~/github/augur_view$ pip install python3-venv
ERROR: Could not find a version that satisfies the requirement python3-venv (from versions: none)
ERROR: No matching distribution found for python3-venv
```

I have some docs to put together for Fedora. I have Augur working on Fedora reliably. Its really a question of keeping our dependencies incredibly up to date, which is not a terrible thing. I guess that's unrelated chit chat.

**Comment by Ulincsys** [comment]
Fixed by c65581e4a882c207ebc4b7a0442ae1bc14b5f351
