### ISSUE TITLE
Issue with the hyperlink to the corresponding title of repositories in the card view

### ISSUE THREAD

**Issue by ayushtamra** [augurlabs/augur_view#6]
**Description:**
The hyperlink corresponding to the title of any repository in the card view directs towards the actual repository on Github, which is in the table view shows the reports, which probably should happen when someone clicks on it (for the card view)

**How to reproduce:**
1. Go to `http://new.augurlabs.io/`
2. From the repositories icon in navigation bar, shift to the card view
3. Click any of the repository, it will take user to the main Github repository

**Expected behavior:**
It should show the community reports to the user

**Possible fix**:
It can be solved with a minor fix in the templates/repos-card.html

@sgoggins @Ulincsys Would love to make a pr for this, as my first contribution in augur

**Comment by Ulincsys** [comment]
Hello Ayush!

Thank you for the very descriptive and well formatted issue 😁 We are planning to merge dev into main shortly, if you'd still like to get this change in we'd be happy to have a pr on dev for it in the next few days.

**Comment by ayushtamra** [comment]
Thanks for the feedback John! Actually I didn't previously saw the dev branch and now I am actually looking at its code, but I think the change is already been made with this [commit](https://github.com/augurlabs/augur_view/commit/dbed6c4cf096eef035bcd03aa9b86cc710e9e6ae#diff-b85dbfdd0285541f8254fef0e2e1466e27514b35d902c918aef4c82d4680580b)

Its totally fine tho, I am actually very interested to contribute to the augur_view and I am currently understanding it,
looking forward to contributing in this with your guidance😊

**Comment by Ulincsys** [comment]
Fixed by dbed6c4cf096eef035bcd03aa9b86cc710e9e6ae
